version: '3'

networks:
  default:
    external:
      name: sun-net
services:
  sun-spring-admin:
    build: .
    container_name: sun-spring-admin
    networks:
        default:
            ipv4_address: 172.18.0.3
    ports:
      - "9665"
      
  sun-spring-test01:
    build: ../sunSpringTest01
    container_name: sun-spring-test01
    networks:
        default:
            ipv4_address: 172.18.0.5
    ports:
      - "9666"
      
  sun-rabbit01:
    image: rabbitmq:3.8-rc-management-alpine
    container_name: sun-rabbit01
    networks:
        default:
            ipv4_address: 172.18.0.6
            
  sun-eureka01:
    build: ../sunnyEurekaServer
    container_name: sun-eureka01
    networks:
        default:
            ipv4_address: 172.18.0.9
    ports:
      - "9669"